name: suits
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  pin_code_fields: ^8.0.1
  lottie: ^3.1.2
  clipboard: ^2.0.2
  flutter_screenutil: ^5.9.3
  animate_do: ^4.2.0
  dio: ^5.9.0
  google_maps_flutter: ^2.14.0
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0  

 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ 
    - assets/images/
    

  



  fonts:
    - family: Waterfall
      fonts:
        - asset: assets/fonts/Waterfall.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    